version: "3.9"
services:
  web:
    container_name: squad-app
    build: .
    restart: always
    ports:
      - 5000:5000
    environment:
      - FLASK_DEBUG=1
    volumes:
      - .:/app

    networks:
        - backend

  db:
    image: mysql:5.7
    volumes:
        - ./database:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: squad_test  
    ports: 
      - 3306:3306
    networks:
        - backend

networks:
    backend:

volumes:
    database: